n = "50"
t1 = "2.7"
d_min = "2"
d_max = "10"
d_max_iter = "1000"
t2 = "2.7"
c_min = "4"
c_max = "50"
c_max_iter = "1000"
mu = "0.1"
islocal = "false"
isCL = "false"
nout = "0"
seed = ""
degreefile = "info/deg.dat"
communitysizesfile = "info/cs.dat"
communityfile = "info/com.dat"
networkfile = "info/edge.dat"
