n = "10000"
t1 = "3"
d_min = "5"
d_max = "50"
d_max_iter = "1000"
t2 = "2"
c_min = "50"
c_max = "1000"
c_max_iter = "1000"
mu = "0.2"
islocal = "false"
isCL = "false"
nout = "0"
seed = ""
degreefile = "Data_Graph/deg.dat"
communitysizesfile = "Data_Graph/cs.dat"
communityfile = "Data_Graph/com.dat"
networkfile = "Data_Graph/edge.dat"
