n = "10000"
t1 = "3"
d_min = "5"
d_max = "50"
d_max_iter = "1000"
t2 = "2"
c_min = "50"
c_max = "1000"
c_max_iter = "1000"
xi = "0.2"
islocal = "false"
isCL = "false"
degreefile = "networks/deg.dat"
communitysizesfile = "networks/cs.dat"
communityfile = "networks/com.dat"
networkfile = "networks/edge.dat"
seed = ""
